/**
 * TopicNode — a single rich node in the nodx network graph.
 *
 * Inspired by ComfyUI's node design: dark card with a colored header strip
 * (status indicator), title, optional emoji, a body section showing the
 * AI summary, and bottom-row chips for message count / child count /
 * open-questions flag. Input port on the left (parent edge in), output
 * port on the right (children edge out).
 *
 * The wrapper element handles its own click/double-click via React, so the
 * NetworkGraphView only needs to wire node positions/edges.
 */

import { memo } from 'react';
import { Handle, Position, type NodeProps } from '@xyflow/react';
import type { TopicNodeKind, TopicStatus } from '@nodx/models';
import { useT } from '../../i18n/index.js';
import type { StringKey } from '../../i18n/index.js';

export interface TopicNodeData extends Record<string, unknown> {
  title: string;
  status: TopicStatus;
  isPinned: boolean;
  aiSummary?: string;
  messageCount: number;
  childCount: number;
  hasOpenQuestions: boolean;
  isSelected: boolean;
  isArchived: boolean;
  /** When true, the node was generated by an auto-recursion run — show ghost styling. */
  isAutoRecursion: boolean;
  /** 思考 vs 执行 — execution nodes get a distinct green/checklist styling. */
  nodeKind: TopicNodeKind;
  /** How many 素材 are wired into this node (drives the 综合 button). */
  linkedMaterialCount: number;
  /** Open the 素材综合 modal for this topic. */
  onSynthesize: (topicId: string) => void;
}

const STATUS_META: Record<
  TopicStatus,
  { labelKey: StringKey; dot: string; ring: string; tint: string }
> = {
  exploring: {
    labelKey: 'graph.status.exploring',
    dot: 'bg-blue-400',
    ring: 'shadow-[0_0_0_2px_rgba(59,130,246,0.35)]',
    tint: 'from-blue-500/15 to-blue-500/0',
  },
  summarized: {
    labelKey: 'graph.status.summarized',
    dot: 'bg-purple-400',
    ring: 'shadow-[0_0_0_2px_rgba(168,85,247,0.35)]',
    tint: 'from-purple-500/15 to-purple-500/0',
  },
  atomic: {
    labelKey: 'graph.status.atomic',
    dot: 'bg-emerald-400',
    ring: 'shadow-[0_0_0_2px_rgba(16,185,129,0.4)]',
    tint: 'from-emerald-500/20 to-emerald-500/0',
  },
  ghost: {
    labelKey: 'graph.status.ghost',
    dot: 'bg-zinc-500',
    ring: '',
    tint: 'from-zinc-500/10 to-zinc-500/0',
  },
};

function TopicNodeInner({ id, data }: NodeProps) {
  const { t } = useT();
  const d = data as TopicNodeData;
  const isExec = d.nodeKind === 'execution';
  const meta = STATUS_META[d.status];
  const statusLabel = t(meta.labelKey);
  // Execution nodes read as concrete "do this" cards — override to emerald.
  const ring = isExec
    ? 'shadow-[0_0_0_2px_rgba(16,185,129,0.45)]'
    : meta.ring;
  const tint = isExec ? 'from-emerald-500/20 to-emerald-500/0' : meta.tint;
  return (
    <div
      className={
        'group relative rounded-xl border bg-zinc-900 text-zinc-100 ' +
        'w-[240px] select-none cursor-pointer transition-all ' +
        (d.isSelected
          ? (isExec ? 'border-emerald-400 ' : 'border-accent ') +
            ring +
            ' scale-[1.02]'
          : (isExec
              ? 'border-emerald-700/60 hover:border-emerald-500/70 '
              : 'border-zinc-700 hover:border-zinc-500 ') + 'hover:shadow-lg') +
        (d.isAutoRecursion ? ' border-dashed opacity-90' : '')
      }
    >
      {/* Soft tint — status colour, or emerald for execution nodes */}
      <div
        className={
          'absolute inset-0 rounded-xl pointer-events-none bg-gradient-to-br ' +
          tint
        }
      />

      {/* Header strip */}
      <div className="relative flex items-center gap-2 px-3 py-2 border-b border-zinc-700/60">
        {isExec ? (
          <span
            className="text-[10px] px-1.5 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 flex-shrink-0"
            title={t('graph.execTip')}
          >
            {t('graph.execBadge')}
          </span>
        ) : (
          <span
            className={'w-2 h-2 rounded-full flex-shrink-0 ' + meta.dot}
            title={statusLabel}
          />
        )}
        {d.isPinned && (
          <span className="text-amber-400 text-[10px]" title={t('graph.pinnedTip')}>
            📌
          </span>
        )}
        <div
          className="text-[13px] font-semibold truncate flex-1"
          title={d.title}
        >
          {d.title}
        </div>
        {d.hasOpenQuestions && (
          <span
            className="w-2 h-2 rounded-full bg-rose-500 animate-pulse flex-shrink-0"
            title={t('graph.hasBlockersTip')}
          />
        )}
      </div>

      {/* Body — AI summary or fallback hint */}
      <div className="relative px-3 py-2 min-h-[44px]">
        {d.aiSummary ? (
          <div
            className="text-[11.5px] text-zinc-300 leading-snug line-clamp-3"
            title={d.aiSummary}
          >
            {d.aiSummary}
          </div>
        ) : (
          <div className="text-[11px] text-zinc-500 italic leading-snug">
            {t('graph.noSummary')}
          </div>
        )}
      </div>

      {/* 素材综合 — shown when materials are wired into this node */}
      {d.linkedMaterialCount > 0 && (
        <div className="relative px-3 pb-2">
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              d.onSynthesize(id);
            }}
            title={t('graph.synthesizeTip')}
            className="w-full text-[11px] font-medium rounded-md bg-amber-500/20 text-amber-300 border border-amber-500/40 hover:bg-amber-500/30 py-1 transition"
          >
            {t('graph.synthesizeBtn', { n: String(d.linkedMaterialCount) })}
          </button>
        </div>
      )}

      {/* Footer chips — hover any chip for a full label */}
      <div className="relative flex items-center gap-1.5 px-3 py-1.5 border-t border-zinc-700/60 text-[10px] text-zinc-400">
        <span
          className="px-1.5 py-0.5 rounded bg-zinc-800/80"
          title={t('graph.currentStatus', { s: statusLabel })}
        >
          {statusLabel}
        </span>
        {d.messageCount > 0 && (
          <span
            className="px-1.5 py-0.5 rounded bg-zinc-800/80 inline-flex items-center gap-1"
            title={t('graph.msgCountTip', { n: String(d.messageCount) })}
          >
            <span aria-hidden>💬</span>
            <span>{d.messageCount}</span>
          </span>
        )}
        {d.childCount > 0 && (
          <span
            className="px-1.5 py-0.5 rounded bg-zinc-800/80 inline-flex items-center gap-1"
            title={t('graph.childCountTip', { n: String(d.childCount) })}
          >
            <BranchIcon />
            <span>{d.childCount}</span>
          </span>
        )}
        {d.isAutoRecursion && (
          <span
            className="px-1.5 py-0.5 rounded bg-violet-500/20 text-violet-300"
            title={t('graph.autoRecurTip')}
          >
            {t('graph.autoRecurBadge')}
          </span>
        )}
        <span className="ml-auto text-zinc-500 opacity-0 group-hover:opacity-100 transition">
          {t('graph.dblClickEnter')}
        </span>
      </div>

      {/* Input port (from parent) */}
      <Handle
        type="target"
        position={Position.Left}
        className="!w-2.5 !h-2.5 !bg-blue-500 !border-2 !border-zinc-900"
      />
      {/* Output port (to children) */}
      <Handle
        type="source"
        position={Position.Right}
        className="!w-2.5 !h-2.5 !bg-emerald-500 !border-2 !border-zinc-900"
      />
    </div>
  );
}

export const TopicNode = memo(TopicNodeInner);

/**
 * Branch icon — one parent dot on top, three child dots below, connected
 * by smooth curves. Inspired by sitemap / org-chart symbols.
 * Replaces the 🌳 emoji which was visually ambiguous at small sizes.
 * Uses currentColor so it inherits the chip's text colour.
 */
function BranchIcon() {
  return (
    <svg
      width="12"
      height="12"
      viewBox="0 0 16 16"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.2"
      strokeLinecap="round"
      aria-hidden
    >
      {/* curved connectors: parent at (8, 3) → 3 children at the bottom */}
      <path d="M8 4.5 C 8 8, 3 9, 3 11" />
      <path d="M8 4.5 L 8 11" />
      <path d="M8 4.5 C 8 8, 13 9, 13 11" />
      {/* parent dot (slightly bigger) */}
      <circle cx="8" cy="3" r="1.7" fill="currentColor" stroke="none" />
      {/* three child dots */}
      <circle cx="3" cy="12.5" r="1.4" fill="currentColor" stroke="none" />
      <circle cx="8" cy="12.5" r="1.4" fill="currentColor" stroke="none" />
      <circle cx="13" cy="12.5" r="1.4" fill="currentColor" stroke="none" />
    </svg>
  );
}
