/**
 * AI gateway client adapter.
 *
 * In 0.2.0 nodx switched from "Cloudflare worker on :8787 that user starts
 * manually" to "in-process Rust gateway started by Tauri on launch". The
 * frontend still fetches http://localhost:8787 with the same Bearer auth,
 * but:
 *
 *   - The token is generated by Rust per-launch (random, not in .env).
 *     We fetch it on app start via the `ai_gateway_token` Tauri command.
 *   - The actual AI API key (sk-ant-... / etc.) lives in the OS keychain.
 *     The Rust gateway reads it at request time; this file never sees it.
 *   - `.env.local` is no longer needed — the gateway URL defaults to
 *     localhost:8787 which is always the in-proc server.
 *
 * Backwards compat: if VITE_AI_GATEWAY_URL / VITE_AI_CLIENT_TOKEN are set
 * (dev override pointing at the old Cloudflare worker), we honour them.
 */

import { invoke } from '@tauri-apps/api/core';
import {
  complete,
  completeUntilDone,
  completeText,
  completeTextUntilDone,
  embed,
  pingGateway,
  type GatewayConfig,
} from '@nodx/ai';

const ENV_ENDPOINT = import.meta.env.VITE_AI_GATEWAY_URL as string | undefined;
const ENV_TOKEN = import.meta.env.VITE_AI_CLIENT_TOKEN as string | undefined;

const ENDPOINT = ENV_ENDPOINT ?? 'http://localhost:8787';

let cachedConfig: GatewayConfig | null = null;
let tokenPromise: Promise<string> | null = null;

export class AiNotConfiguredError extends Error {
  constructor(message?: string) {
    super(
      message ??
        'AI 未配置。打开「⚙ 设置」→ 填入你的 Anthropic API key（sk-ant-...）即可使用。',
    );
    this.name = 'AiNotConfiguredError';
  }
}

/** True if running inside a Tauri webview (i.e. in-proc gateway is available). */
export function isInTauri(): boolean {
  return typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;
}

/**
 * Get the bearer token. Strategy:
 *
 *   - If we're inside Tauri (the normal desktop case), ALWAYS use the
 *     Rust-generated random token. This avoids the trap where a stale
 *     VITE_AI_CLIENT_TOKEN in .env.local desynchronises from the random
 *     Rust value and every request returns 401.
 *
 *   - Outside Tauri (e.g. running `vite dev` against an external worker,
 *     pre-0.2 setup), fall back to .env.local. Honour both VITE_AI_GATEWAY_URL
 *     (remote worker) and VITE_AI_CLIENT_TOKEN.
 *
 *   - Exception inside Tauri: if VITE_AI_GATEWAY_URL is explicitly set to
 *     a non-localhost URL (i.e. the user wants nodx to talk to a remote
 *     Cloudflare worker instead of the in-proc gateway), use ENV_TOKEN too.
 */
async function getToken(): Promise<string> {
  const usingRemoteEndpoint =
    ENV_ENDPOINT &&
    ENV_ENDPOINT !== '' &&
    !ENV_ENDPOINT.startsWith('http://localhost') &&
    !ENV_ENDPOINT.startsWith('http://127.0.0.1');

  // If user explicitly points at a remote worker, ENV_TOKEN is the source of truth.
  if (usingRemoteEndpoint) {
    if (
      ENV_TOKEN &&
      ENV_TOKEN !== 'replace-me-with-the-same-value-as-worker' &&
      ENV_TOKEN !== ''
    ) {
      return ENV_TOKEN;
    }
    throw new AiNotConfiguredError(
      `VITE_AI_GATEWAY_URL=${ENV_ENDPOINT} 指向远程 worker，但 VITE_AI_CLIENT_TOKEN 未设置。`,
    );
  }

  // Default path: in-proc gateway. ALWAYS use the Rust-generated token,
  // regardless of what .env.local says (it might be stale).
  if (isInTauri()) {
    if (!tokenPromise) {
      tokenPromise = invoke<string>('ai_gateway_token').then((t) => {
        if (!t) {
          throw new Error(
            'In-proc gateway token not set yet — try again in a moment.',
          );
        }
        return t;
      });
    }
    return tokenPromise;
  }

  // Non-Tauri (browser / SSR) — fall back to env.
  if (
    ENV_TOKEN &&
    ENV_TOKEN !== 'replace-me-with-the-same-value-as-worker' &&
    ENV_TOKEN !== ''
  ) {
    return ENV_TOKEN;
  }
  throw new AiNotConfiguredError();
}

/**
 * Resolve a GatewayConfig usable by `@nodx/ai`. Async because we may need
 * to invoke a Tauri command to fetch the token.
 */
export async function getGatewayConfig(): Promise<GatewayConfig> {
  if (cachedConfig) return cachedConfig;
  const clientToken = await getToken();
  cachedConfig = { endpoint: ENDPOINT, clientToken };
  return cachedConfig;
}

/**
 * Synchronous "is the AI surface usable?" check. Pre-0.2 this answered "is
 * the env token set?"; in the in-proc model the gateway always exists once
 * Tauri is up, so we return true inside the Tauri webview and let the real
 * "no key" failure surface as a 402 → friendly Settings prompt downstream.
 *
 * Kept for callers like `cbr.ts` / `CenterPanel.tsx` that disable a button
 * if AI is fundamentally unavailable — outside a Tauri build (e.g. SSR /
 * tests) the answer is whether ENV_TOKEN is set.
 */
export function isAiConfigured(): boolean {
  if (isInTauri()) return true;
  return !!ENV_TOKEN;
}

/**
 * Async — actually look up whether the user has an Anthropic key in the
 * keychain. Use this when you want to show a "go set up your key" hint.
 */
export async function isAnthropicKeyConfigured(): Promise<boolean> {
  if (!isInTauri()) return !!ENV_TOKEN;
  try {
    return await invoke<boolean>('ai_key_has', { provider: 'anthropic' });
  } catch {
    return false;
  }
}

export type AiProvider = 'anthropic' | 'openai' | 'gemini';

export async function setAiKey(provider: AiProvider, key: string): Promise<void> {
  if (!isInTauri()) {
    throw new Error('Keychain is only available in the Tauri build.');
  }
  await invoke('ai_key_set', { provider, key });
}

export async function hasAiKey(provider: AiProvider): Promise<boolean> {
  if (!isInTauri()) return false;
  try {
    return await invoke<boolean>('ai_key_has', { provider });
  } catch {
    return false;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// AI mode (api_key | cli) — pick which backend services completions.
// ─────────────────────────────────────────────────────────────────────────────

export type AiMode = 'api_key' | 'cli';

/** Read current mode. Defaults to api_key if Tauri unavailable. */
export async function getAiMode(): Promise<AiMode> {
  if (!isInTauri()) return 'api_key';
  try {
    const m = await invoke<string>('ai_mode_get');
    return m === 'cli' ? 'cli' : 'api_key';
  } catch {
    return 'api_key';
  }
}

/** Persist a new mode. Takes effect immediately for the next AI call. */
export async function setAiMode(mode: AiMode): Promise<void> {
  if (!isInTauri()) return;
  await invoke('ai_mode_set', { mode });
}

/**
 * Probe whether `claude` CLI is installed + on PATH. Returns the version
 * string on success, throws otherwise.
 */
export async function detectClaudeCli(): Promise<string> {
  if (!isInTauri()) throw new Error('Only available in Tauri build');
  return invoke<string>('cli_detect');
}

/**
 * Usage tap — every completion through `ai.*` reports (modelId, token usage)
 * to registered listeners. The auto-recursion budget meter (PRD §3.19)
 * subscribes for the duration of a run to accumulate real spend. Attribution
 * assumes other AI surfaces stay quiet while a run is active.
 */
export type AiUsageListener = (
  model: string,
  usage: { inputTokens: number; outputTokens: number },
) => void;

const usageListeners = new Set<AiUsageListener>();

/** Subscribe to all gateway token usage. Returns an unsubscribe function. */
export function onAiUsage(listener: AiUsageListener): () => void {
  usageListeners.add(listener);
  return () => {
    usageListeners.delete(listener);
  };
}

function emitUsage(
  model: string,
  usage: { inputTokens: number; outputTokens: number },
): void {
  for (const l of usageListeners) {
    try {
      l(model, usage);
    } catch {
      // a broken listener must never break the AI call path
    }
  }
}

/**
 * Bound versions that pull config from env / Tauri so call sites don't
 * repeat themselves.
 */
export const ai = {
  async complete<T>(
    opts: Parameters<typeof complete<T>>[1],
  ): ReturnType<typeof complete<T>> {
    const cfg = await getGatewayConfig();
    const r = await complete<T>(cfg, opts);
    emitUsage(opts.model, r.usage);
    return r;
  },

  async completeUntilDone<T>(
    opts: Parameters<typeof completeUntilDone<T>>[1],
  ): ReturnType<typeof completeUntilDone<T>> {
    const cfg = await getGatewayConfig();
    const r = await completeUntilDone<T>(cfg, opts);
    emitUsage(opts.model, r.usage);
    return r;
  },

  async completeText(
    opts: Parameters<typeof completeText>[1],
  ): ReturnType<typeof completeText> {
    const cfg = await getGatewayConfig();
    const r = await completeText(cfg, opts);
    emitUsage(opts.model, r.usage);
    return r;
  },

  async completeTextUntilDone(
    opts: Parameters<typeof completeTextUntilDone>[1],
  ): ReturnType<typeof completeTextUntilDone> {
    const cfg = await getGatewayConfig();
    const r = await completeTextUntilDone(cfg, opts);
    emitUsage(opts.model, r.usage);
    return r;
  },

  async embed(
    opts: Parameters<typeof embed>[1],
  ): ReturnType<typeof embed> {
    const cfg = await getGatewayConfig();
    return embed(cfg, opts);
  },

  async ping(): Promise<boolean> {
    try {
      const cfg = await getGatewayConfig();
      return await pingGateway(cfg);
    } catch {
      return false;
    }
  },
};
